---
# yamllint disable rule:line-length

update_code_slot:
  name: Update code slot information
  description: Update the data that RentalControl has about a given code slot
  fields:
    lockname:
      name: Lock
      description: The lock name that you specified during RentalControl configuration.
      example: frontdoor
      required: true
      selector:
        text:
    slot:
      name: Code Slot
      description: The code slot that you are updating RentalControl about
      example: 11
      required: true
      selector:
        text:
    slot_code:
      name: Door code
      description: The code currently assigned to the slot
      example: 1234
      required: true
      selector:
        text:
    slot_name:
      name: Code Slot Name
      description: The name information on the code slot that you are updating RentalControl about
      example: Mary
      required: true
      selector:
        text:
    start_time:
      name: Slot Start Time
      description: The starting time of the slot that you are updating RentalControl about (just the time)
      example: 16:00
      required: true
      selector:
        datetime:
    end_time:
      name: Slot End Time
      description: The ending time of the slot that you are updating RentalControl about (just the time)
      example: 11:00
      required: true
      selector:
        datetime:
